-- Manual one-time DB setup — paste this whole file into your Postgres provider's web SQL
-- console (Vercel Storage → your DB → Query tab, or Neon's console if that's the underlying
-- provider). Generated by hand from schema.prisma because this environment has no shell/CLI
-- access to run `prisma migrate dev` itself.
--
-- This creates every table + index from schema.prisma (including the two partial indexes
-- Prisma's DSL can't express), then seeds the same fixed-UUID fixture prisma/seed.js would:
-- one location, one admin user (password NOT set yet — see the note at the bottom), 3 chargers.
--
-- Caveat: this bypasses Prisma's own migration history (_prisma_migrations table). Prisma
-- Client will work against it fine either way. If you later want to run `prisma migrate dev`
-- for a schema change, baseline first with `prisma migrate resolve --applied <name>` so Prisma
-- doesn't try to re-run this as a new migration.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ── Tables (FK dependency order) ────────────────────────────────────────────

CREATE TABLE locations (
  id         TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name       TEXT NOT NULL,
  timezone   TEXT NOT NULL DEFAULT 'America/Los_Angeles',
  address    TEXT,
  site_lat   DOUBLE PRECISION,
  site_lng   DOUBLE PRECISION,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id                  TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id         TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  email               TEXT NOT NULL UNIQUE,
  password_hash       TEXT,
  display_name        TEXT NOT NULL,
  role                TEXT NOT NULL DEFAULT 'user',
  vehicle_description TEXT,
  notification_prefs  JSONB NOT NULL DEFAULT '{}',
  carpool_credits     INTEGER NOT NULL DEFAULT 0,
  active              BOOLEAN NOT NULL DEFAULT true,
  failed_attempts     INTEGER NOT NULL DEFAULT 0,
  locked_until        TIMESTAMP(3),
  last_active_at      TIMESTAMP(3),
  created_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_users_location_id ON users(location_id);
CREATE INDEX idx_users_email ON users(email);

CREATE TABLE refresh_tokens (
  id         TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL,
  expires_at TIMESTAMP(3) NOT NULL,
  revoked    BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_token_hash ON refresh_tokens(token_hash);

CREATE TABLE chargers (
  id             TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id    TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  name           TEXT NOT NULL,
  position       INTEGER NOT NULL DEFAULT 0,
  status         TEXT NOT NULL DEFAULT 'available',
  offline_reason TEXT,
  created_at     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_chargers_location_id ON chargers(location_id);

CREATE TABLE sessions (
  id                   TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id          TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  charger_id           TEXT NOT NULL REFERENCES chargers(id) ON DELETE CASCADE,
  user_id              TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status               TEXT NOT NULL DEFAULT 'active',
  vehicle_description  TEXT,
  started_at           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  eta_at               TIMESTAMP(3) NOT NULL,
  ended_at             TIMESTAMP(3),
  overtime_notified_at TIMESTAMP(3),
  created_at           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_sessions_charger_id ON sessions(charger_id);
CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_status ON sessions(status);
CREATE INDEX idx_sessions_started_at ON sessions(started_at);

CREATE TABLE queue_entries (
  id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id     TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  charger_id      TEXT REFERENCES chargers(id) ON DELETE CASCADE,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status          TEXT NOT NULL DEFAULT 'waiting',
  priority        INTEGER NOT NULL DEFAULT 0,
  priority_source TEXT,
  notified_at     TIMESTAMP(3),
  claimed_at      TIMESTAMP(3),
  expires_at      TIMESTAMP(3),
  joined_at       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_queue_entries_charger_id ON queue_entries(charger_id);
CREATE INDEX idx_queue_entries_user_id ON queue_entries(user_id);
CREATE INDEX idx_queue_entries_status ON queue_entries(status);

CREATE TABLE notifications (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,
  priority    TEXT NOT NULL DEFAULT 'normal',
  title       TEXT NOT NULL,
  body        TEXT NOT NULL,
  action_url  TEXT,
  metadata    JSONB NOT NULL DEFAULT '{}',
  read_at     TIMESTAMP(3),
  created_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notifications_user_created ON notifications(user_id, created_at DESC);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);

CREATE TABLE push_subscriptions (
  id         TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint   TEXT NOT NULL UNIQUE,
  p256dh     TEXT NOT NULL,
  auth       TEXT NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_push_subscriptions_user_id ON push_subscriptions(user_id);

CREATE TABLE messages (
  id           TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id  TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  kind         TEXT NOT NULL,
  sender_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recipient_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  charger_id   TEXT REFERENCES chargers(id) ON DELETE SET NULL,
  session_id   TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  body         TEXT,
  metadata     JSONB NOT NULL DEFAULT '{}',
  reaction     TEXT,
  created_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_messages_recipient_created ON messages(recipient_id, created_at DESC);
CREATE INDEX idx_messages_sender_created ON messages(sender_id, created_at DESC);

CREATE TABLE emergency_requests (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reason      TEXT NOT NULL,
  explanation TEXT,
  status      TEXT NOT NULL DEFAULT 'open',
  expires_at  TIMESTAMP(3) NOT NULL,
  created_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_emergency_requests_user_created ON emergency_requests(user_id, created_at DESC);

CREATE TABLE announcements (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  body        TEXT NOT NULL,
  active      BOOLEAN NOT NULL DEFAULT true,
  expires_at  TIMESTAMP(3),
  created_by  TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_announcements_location_active ON announcements(location_id, active);

CREATE TABLE settings (
  location_id TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  key         TEXT NOT NULL,
  value       JSONB NOT NULL,
  updated_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (location_id, key)
);

CREATE TABLE audit_log (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id TEXT REFERENCES locations(id) ON DELETE CASCADE,
  user_id     TEXT REFERENCES users(id) ON DELETE SET NULL,
  action      TEXT NOT NULL,
  details     JSONB NOT NULL DEFAULT '{}',
  created_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_log_location_created ON audit_log(location_id, created_at DESC);
CREATE INDEX idx_audit_log_action ON audit_log(action);

CREATE TABLE carpool_groups (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  description TEXT,
  created_by  TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_carpool_groups_location_id ON carpool_groups(location_id);

CREATE TABLE carpool_group_members (
  group_id  TEXT NOT NULL REFERENCES carpool_groups(id) ON DELETE CASCADE,
  user_id   TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (group_id, user_id)
);

CREATE TABLE carpool_schedules (
  id           TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id  TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role         TEXT NOT NULL,
  direction    TEXT NOT NULL,
  days_of_week INTEGER[] NOT NULL,
  depart_time  TEXT NOT NULL,
  origin_label TEXT NOT NULL,
  origin_lat   DOUBLE PRECISION NOT NULL,
  origin_lng   DOUBLE PRECISION NOT NULL,
  seats        INTEGER NOT NULL DEFAULT 1,
  group_id     TEXT REFERENCES carpool_groups(id) ON DELETE SET NULL,
  active       BOOLEAN NOT NULL DEFAULT true,
  created_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_carpool_schedules_user_id ON carpool_schedules(user_id);
CREATE INDEX idx_carpool_schedules_location_active ON carpool_schedules(location_id, active);

CREATE TABLE carpool_rides (
  id                TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id       TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  driver_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  direction         TEXT NOT NULL,
  origin_label      TEXT NOT NULL,
  origin_lat        DOUBLE PRECISION NOT NULL,
  origin_lng        DOUBLE PRECISION NOT NULL,
  depart_at         TIMESTAMP(3) NOT NULL,
  seats_total       INTEGER NOT NULL,
  seats_available   INTEGER NOT NULL,
  status            TEXT NOT NULL DEFAULT 'open',
  notes             TEXT,
  schedule_id       TEXT REFERENCES carpool_schedules(id) ON DELETE SET NULL,
  linked_session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  group_id          TEXT REFERENCES carpool_groups(id) ON DELETE SET NULL,
  miles             DOUBLE PRECISION,
  co2_grams_saved   DOUBLE PRECISION,
  completed_at      TIMESTAMP(3),
  created_at        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_carpool_rides_location_id ON carpool_rides(location_id);
CREATE INDEX idx_carpool_rides_driver_id ON carpool_rides(driver_id);
CREATE INDEX idx_carpool_rides_status ON carpool_rides(status);
CREATE INDEX idx_carpool_rides_depart_at ON carpool_rides(depart_at);

CREATE TABLE carpool_bookings (
  id           TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id  TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  ride_id      TEXT NOT NULL REFERENCES carpool_rides(id) ON DELETE CASCADE,
  rider_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status       TEXT NOT NULL DEFAULT 'requested',
  seats        INTEGER NOT NULL DEFAULT 1,
  pickup_label TEXT,
  pickup_lat   DOUBLE PRECISION,
  pickup_lng   DOUBLE PRECISION,
  created_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (ride_id, rider_id)
);
CREATE INDEX idx_carpool_bookings_ride_id ON carpool_bookings(ride_id);
CREATE INDEX idx_carpool_bookings_rider_id ON carpool_bookings(rider_id);
CREATE INDEX idx_carpool_bookings_status ON carpool_bookings(status);

CREATE TABLE carpool_requests (
  id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id     TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  rider_id        TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  direction       TEXT NOT NULL,
  origin_label    TEXT NOT NULL,
  origin_lat      DOUBLE PRECISION NOT NULL,
  origin_lng      DOUBLE PRECISION NOT NULL,
  window_start    TIMESTAMP(3) NOT NULL,
  window_end      TIMESTAMP(3) NOT NULL,
  status          TEXT NOT NULL DEFAULT 'open',
  matched_ride_id TEXT REFERENCES carpool_rides(id) ON DELETE SET NULL,
  schedule_id     TEXT REFERENCES carpool_schedules(id) ON DELETE SET NULL,
  group_id        TEXT REFERENCES carpool_groups(id) ON DELETE SET NULL,
  created_at      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_carpool_requests_rider_id ON carpool_requests(rider_id);
CREATE INDEX idx_carpool_requests_location_status ON carpool_requests(location_id, status);

CREATE TABLE carpool_trip_logs (
  id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id     TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  ride_id         TEXT NOT NULL REFERENCES carpool_rides(id) ON DELETE CASCADE,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role            TEXT NOT NULL,
  miles           DOUBLE PRECISION NOT NULL DEFAULT 0,
  co2_grams_saved DOUBLE PRECISION NOT NULL DEFAULT 0,
  credits_awarded INTEGER NOT NULL DEFAULT 0,
  created_at      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_carpool_trip_logs_user_created ON carpool_trip_logs(user_id, created_at DESC);
CREATE INDEX idx_carpool_trip_logs_location_created ON carpool_trip_logs(location_id, created_at DESC);
CREATE INDEX idx_carpool_trip_logs_ride_id ON carpool_trip_logs(ride_id);

CREATE TABLE carpool_credits_ledger (
  id            TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  location_id   TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind          TEXT NOT NULL,
  amount        INTEGER NOT NULL,
  reason        TEXT NOT NULL,
  balance_after INTEGER NOT NULL,
  ride_id       TEXT REFERENCES carpool_rides(id) ON DELETE SET NULL,
  created_at    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_carpool_credits_ledger_user_created ON carpool_credits_ledger(user_id, created_at DESC);

-- ── Hand-authored partial indexes (can't be expressed in schema.prisma's DSL) ──────────────

CREATE UNIQUE INDEX uniq_active_session_per_charger
  ON sessions(charger_id) WHERE status IN ('active', 'overtime');

CREATE INDEX idx_queue_order
  ON queue_entries(charger_id, priority DESC, joined_at ASC) WHERE status = 'waiting';

-- ── Seed data (same fixed UUIDs as prisma/seed.js) ──────────────────────────────────────────
-- Settings are intentionally NOT seeded — configService falls back to shared/constants.js's
-- SETTING_DEFAULTS when no row exists, so this is not a gap.

INSERT INTO locations (id, name, timezone, address, site_lat, site_lng)
VALUES (
  '11111111-1111-1111-1111-111111111111',
  'Astera Labs HQ',
  'America/Los_Angeles',
  '2953 Bunker Hill Ln, Santa Clara, CA',
  37.3541,
  -121.9552
)
ON CONFLICT (id) DO NOTHING;

-- password_hash is left NULL here — a real bcrypt hash can't be computed without running
-- code. After this script runs, from server/ (with .env pointed at this DB) run:
--   npm install && npm run seed:admin
-- which sets a real password (default ChangeMe123!, or `npm run seed:admin "MyPassword1!"`).
-- Login will 401 until that command runs.
INSERT INTO users (id, location_id, email, password_hash, display_name, role)
VALUES (
  '22222222-2222-2222-2222-222222222222',
  '11111111-1111-1111-1111-111111111111',
  'admin@asteralabs.com',
  NULL,
  'Site Admin',
  'admin'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO chargers (location_id, name, position)
SELECT '11111111-1111-1111-1111-111111111111', v.name, v.position
FROM (VALUES ('Charger 1', 1), ('Charger 2', 2), ('Charger 3', 3)) AS v(name, position)
WHERE NOT EXISTS (
  SELECT 1 FROM chargers
  WHERE location_id = '11111111-1111-1111-1111-111111111111' AND name = v.name
);
